/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pinger.h"

bool_t
xdr_hostStateOptions (XDR *xdrs, hostStateOptions *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hostState (XDR *xdrs, hostState *objp)
{
	register int32_t *buf;

	 if (!xdr_hostStateOptions (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_timeout (XDR *xdrs, timeout *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hostName (XDR *xdrs, hostName objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hostInfo (XDR *xdrs, hostInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_hostName (xdrs, objp->host))
		 return FALSE;
	 if (!xdr_timeout (xdrs, &objp->duration))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hostStatus (XDR *xdrs, hostStatus *objp)
{
	register int32_t *buf;

	 if (!xdr_hostInfo (xdrs, &objp->host))
		 return FALSE;
	 if (!xdr_hostState (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hostsList (XDR *xdrs, hostsList *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->hostsList_val, (u_int *) &objp->hostsList_len, ~0,
		sizeof (hostStatus), (xdrproc_t) xdr_hostStatus))
		 return FALSE;
	return TRUE;
}
